<?php


namespace Firesphere\ISO27001Compliance\Pages;


use Firesphere\ISO27001Compliance\Controllers\AnnexPageController;
use Firesphere\ISO27001Compliance\Models\AnnexSet;
use Page;

/**
 * Class \Firesphere\ISO27001Compliance\Pages\AnnexPage
 *
 * @property int $AnnexID
 * @method AnnexSet Annex()
 */
class AnnexPage extends Page
{
    private static $table_name = 'ISO27k1AnnexPage';

    private static $has_one = [
        'Annex' => AnnexSet::class,
    ];

    public function onBeforeWrite()
    {
        if (!$this->AnnexID) {
            $annex = AnnexSet::create(['Title' => $this->Title . ' Annex']);
            $this->AnnexID = $annex->write();
        }
        parent::onBeforeWrite();
    }

    public function getControllerName()
    {
        return AnnexPageController::class;
    }

    public function canCreate($member = null, $context = [])
    {
        if (self::get()->count()) {
            return false;
        }

        return parent::canCreate($member, $context); // TODO: Change the autogenerated stub
    }
}
