<?php


namespace Firesphere\ISO27001Compliance\Models;


use Firesphere\ISO27001Compliance\Pages\AnnexPage;
use SilverStripe\ORM\DataObject;

/**
 * Class \Firesphere\ISO27001Compliance\Models\RASCI
 *
 * @property string $Value
 * @property int $TeamID
 * @property int $SubsidiaryID
 * @property int $AnnexPageID
 * @method Team Team()
 * @method Subsidiary Subsidiary()
 * @method AnnexPage AnnexPage()
 */
class RASCI extends DataObject
{
    private static $table_name = 'ISO27k1RASCI';

    private static $db = [
        'Value' => 'Enum(",R,A,S,C,I")',
    ];

    private static $has_one = [
        'Team'       => Team::class,
        'Subsidiary' => Subsidiary::class,
        'AnnexPage'  => AnnexPage::class,
    ];

    public static function findOrCreate($value, $team, $subsidiary, $pageID)
    {
        $data = [
            'TeamID'       => $team,
            'SubsidiaryID' => $subsidiary,
            'AnnexPageID'  => $pageID,
        ];
        $self = self::get()->filter($data)->first();
        if (!$self) {
            $self = self::create();
        }
        return $self->update(array_merge(
                $data,
                ['Value' => $value]
            )
        )->write();
    }

    public function canEdit($member = null)
    {
        return parent::canEdit($member); // TODO: Change the autogenerated stub
    }
}
